name: Shell Lint

# Lint on every push and on PRs that touch shell files or the Makefile
on:
  push:
    paths:
      - "**.sh"
      - "Makefile"
  pull_request:
    paths:
      - "**.sh"
      - "Makefile"

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Install shellcheck & make
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y shellcheck make

      - name: Run shellcheck via Makefile
        run: make shellcheck
